# Generated by Django 4.2.4 on 2023-08-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dht22',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heatindex', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dht22',
                'managed': False,
            },
        ),
    ]
